In [18]:
import re
import requests
import xml.etree.ElementTree as ET
import pandas as pd
from camel_tools.morphology.database import MorphologyDB
from camel_tools.morphology.analyzer import Analyzer
import os
import json
import html
import time

In [29]:
import requests
from bs4 import BeautifulSoup
import json

url = "https://quranwbw.com/duas"
res = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
soup = BeautifulSoup(res.text, "html.parser")

duas = []

for verse in soup.select("div.verse"):
    verse_id = verse.get("id")  # e.g. "2:127"
    if not verse_id:
        continue

    # Arabic (join all words)
    arabic_words = [
        w.get_text(strip=True)
        for w in verse.select(".word .arabicText")
    ]
    arabic = " ".join(arabic_words)

    # Transliteration + translation
    blocks = verse.select(".verseTranslationText > div")
    transliteration = ""
    translation = ""

    if len(blocks) > 0:
        transliteration = blocks[0].find("span").get_text(strip=True)

    if len(blocks) > 1:
        translation = blocks[1].find("span").get_text(strip=True)

    duas.append({
        "reference": verse_id,
        "arabic": arabic,
        "transliteration": transliteration,
        "translation": translation
    })

with open("quranwbw_duas.json", "w", encoding="utf-8") as f:
    json.dump(duas, f, ensure_ascii=False, indent=2)

print(f"Extracted {len(duas)} duas")

Extracted 0 duas

In [33]:
from playwright.sync_api import sync_playwright
import json

with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page()
    page.goto("https://quranwbw.com/duas", timeout=60000)

    page.wait_for_selector("div.verse")

    verses = page.query_selector_all("div.verse")
    duas = []

    for verse in verses:
        verse_id = verse.get_attribute("id")

        arabic_words = verse.query_selector_all(".word .arabicText")
        arabic = " ".join([w.inner_text().strip() for w in arabic_words])

        blocks = verse.query_selector_all(".verseTranslationText > div")

        transliteration = blocks[0].inner_text().split("—")[0].strip() if len(blocks) > 0 else ""
        translation     = blocks[1].inner_text().split("—")[0].strip() if len(blocks) > 1 else ""

        duas.append({
            "reference": verse_id,
            "arabic": arabic,
            "transliteration": transliteration,
            "translation": translation
        })

    browser.close()

with open("quranwbw_duas.json", "w", encoding="utf-8") as f:
    json.dump(duas, f, ensure_ascii=False, indent=2)

print("Extracted", len(duas), "duas")

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

In [34]:
import asyncio
from playwright.async_api import async_playwright
import json

In [35]:
async def scrape_duas():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        await page.goto("https://quranwbw.com/duas", timeout=60000)
        await page.wait_for_selector("div.verse")

        verses = await page.query_selector_all("div.verse")
        print("Found verses:", len(verses))

        duas = []

        for verse in verses:
            verse_id = await verse.get_attribute("id")
            if not verse_id:
                continue

            # Arabic words
            words = await verse.query_selector_all(".word .arabicText")
            arabic = " ".join([ (await w.inner_text()).strip() for w in words ])

            blocks = await verse.query_selector_all(".verseTranslationText > div")

            transliteration = ""
            translation = ""

            if len(blocks) > 0:
                transliteration = (await blocks[0].inner_text()).split("—")[0].strip()

            if len(blocks) > 1:
                translation = (await blocks[1].inner_text()).split("—")[0].strip()

            duas.append({
                "reference": verse_id,
                "arabic": arabic,
                "transliteration": transliteration,
                "translation": translation
            })

        await browser.close()

        with open("quranwbw_duas.json", "w", encoding="utf-8") as f:
            json.dump(duas, f, ensure_ascii=False, indent=2)

        print("Extracted", len(duas), "duas")


# Run it safely inside existing event loop
await scrape_duas()

NotImplementedError:

In [36]:
import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())

In [37]:
await scrape_duas()

NotImplementedError:

In [19]:
exec(open("ayah_from_api.py", encoding="utf-8").read())

In [20]:
exec(open("tag_expain.py", encoding="utf-8").read())

In [21]:
exec(open("xml_data_parser.py", encoding="utf-8").read())

🧾 Total Surahs: 114 (Expected: 114)

📊 Ayahs per Surah (first 10):
Surah
1       7
2     286
3     200
4     176
5     120
6     165
7     206
8      75
9     129
10    109
Name: Ayah, dtype: int64

🔢 Total Unique Ayahs: 6236 (Expected: ~6236)

📝 Words per Ayah - min: 1, max: 128, avg: 12.42

✅ Structure verification complete.

In [22]:
import warnings
warnings.filterwarnings("ignore")
exec(open("df_morph_builder.py", encoding="utf-8").read())

In [23]:
import warnings
warnings.filterwarnings("ignore")
exec(open("main_data_parer.py", encoding="utf-8").read())

In [7]:
exec(open("html_run_from_local.py", encoding="utf-8").read())
get_final_ayah_game(2,2)

NameError: name 'get_final_ayah_game' is not defined

In [24]:
exec(open("games_python.py", encoding="utf-8").read())
get_final_ayah_game(2,2)

✅ HTML file generated: output\surah_2\ayah_2_2.html

In [14]:
with open("games_python.py", "r", encoding="utf-8-sig") as f:
    content = f.read()

with open("games_python.py", "w", encoding="utf-8") as f:
    f.write(content)

In [124]:
import pandas as pd

df = pd.read_excel("verbs_with_meanings_roots.xlsx")
df = df.dropna(subset=["Arabic", "verse_key", "meaning"])

def get_rank(verse_key):
    surah, ayah = map(int, verse_key.split(":"))
    return surah * 1000 + ayah

df["rank"] = df["verse_key"].apply(get_rank)

with open("verb_data.js", "w", encoding="utf-8") as f:
    f.write("const VERB_DATA = {\n")
    for _, row in df.iterrows():
        verb = row["Arabic"]
        rank = row["rank"]
        meaning = row["meaning"].strip()
        f.write(f'  "{verb}": {{ rank: {rank}, meaning: "{meaning}" }},\n')
    f.write("};")

In [837]:
import pandas as pd
import json

df = pd.read_excel("verbs_with_meanings_roots.xlsx")
df = df[["3MSAP_root", "meaning"]].dropna()

# Ensure valid strings
df["3MSAP_root"] = df["3MSAP_root"].astype(str).str.strip()
df["meaning"] = df["meaning"].astype(str).str.strip()

# Create list of dicts
data = df.to_dict(orient="records")

# Output to JS-ready JSON format
with open("verb_data.js", "w", encoding="utf-8") as f:
    f.write("const dataset = ")
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write(";")

In [120]:
import pandas as pd
import numpy as np

# Load Excel
df = pd.read_excel("test_2.xlsx", sheet_name="cert_atrt")
col1 = "TOTAL_COUNT"
col2 = "wt_dev"

target1 = 3681.0  # Real decimal
target2 = 1043.3678335398563  # Real decimal

# Use real values
a_vals = df[col1].values
b_vals = df[col2].values
n = len(df)

# Sort by contribution
indices = np.argsort((a_vals / target1 + b_vals / target2))[::-1]

sum_a = 0.0
sum_b = 0.0
picked = []

for i in indices:
    if sum_a + a_vals[i] <= target1 and sum_b + b_vals[i] <= target2:
        picked.append(i)
        sum_a += a_vals[i]
        sum_b += b_vals[i]

        # Round sums to 3 decimal places for checking
        if round(sum_a, 3) == round(target1, 3) and round(sum_b, 3) == round(target2, 3):
            break

# Output
if round(sum_a, 0) == round(target1, 0) and round(sum_b, 0) == round(target2, 0):
    selected_df = df.loc[picked]
    print(f"✅ Exact match found in rows: {picked}")
    print(f"Sum A: {sum_a:.0f}, Sum B: {sum_b:.0f}")
    print(selected_df)

    # Save to Excel
    selected_df.to_excel("selected_rows.xlsx", index=False)
    print("✅ Saved selected rows to 'selected_rows.xlsx'")

else:
    print(f"❌ No exact match found. Current sums: A={sum_a:.0f}, B={sum_b:.0f}")

✅ Exact match found in rows: [0, 1, 24, 2, 27, 3, 6, 13, 4, 52, 5, 20, 35, 21, 9, 65, 14, 8, 7, 15, 16, 23, 277, 10, 320, 11, 56, 19, 96, 25, 119, 26, 12, 55, 18, 37, 29, 38, 17, 87, 229, 22, 62, 223, 84, 114, 68, 33, 36, 30, 28, 51, 85, 80, 107, 90, 32, 39, 48, 40, 302, 328, 331, 134, 93, 160, 204, 207, 148, 189, 129, 251, 300, 321, 246, 210, 95, 317, 305, 126, 324, 271, 112, 282, 224, 325, 131, 167, 225, 187, 237, 166]
Sum A: 3681, Sum B: 1043
      client domain                            additional_str_keys_uid  \
0    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ERM PMSEARCH WINDOW...
1    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.AMB_ORG_DAY_VIE...
24   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: PDOC NAVIGATOR DOC...
2    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-OPEN CHART (DIS...
27   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ICU-IVIEW-ADDING A ...
..       ...    ...                                                ...
167  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:SRA SAANESTHESIA SA...
225  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ORM.SEARCHFAVORITES...
187  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-REFRESH VIEW (R...
237  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PHAMEDMGR.CALCULATE...
166  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ORM.CONVERTTOINPATI...

        collection_time  TOTAL_TIME  TOTAL_COUNT  ATRT_AVG  \
0   2025-04-16 13:47:00  171.913284           49  3.508434
1   2025-04-16 13:47:00  146.350030           39  3.752565
24  2025-04-16 13:47:00   39.957892          221  0.180805
2   2025-04-16 13:47:00  128.076467          100  1.280765
27  2025-04-16 13:47:00   36.148561          171  0.211395
..                  ...         ...          ...       ...
167 2025-04-16 13:47:00    4.259410           12  0.354951
225 2025-04-16 13:47:00    0.013680           12  0.001140
187 2025-04-16 13:47:00    1.400767           11  0.127342
237 2025-04-16 13:47:00    0.104996           10  0.010500
166 2025-04-16 13:47:00    4.119056            1  4.119056

                                                    ts  \
0                      USR:ERM PMSEARCH WINDOW LOAD ()
1         USR:MPG.AMB_ORG_DAY_VIEW_RENDER (AGGREGATED)
24                USR: PDOC NAVIGATOR DOC SET CLICK ()
2     USR:PWR-OPEN CHART (DISCERNRPT/DISCERNPCTAB.DLL)
27                    USR:ICU-IVIEW-ADDING A RESULT ()
..                                                 ...
167  USR:SRA SAANESTHESIA SAVE AND REFRESH RECORDS ...
225                     USR:ORM.SEARCHFAVORITESITEM ()
187    USR:PWR-REFRESH VIEW (REFRESHING TASK LIST TAB)
237          USR:PHAMEDMGR.CALCULATE ORDER SCHEDULE ()
166  USR:ORM.CONVERTTOINPATIENTMR-CONVERTORDER (NO ...

                                       check _in_prod?        ga  \
0                      USR:ERM PMSEARCH WINDOW LOAD ()  0.333472
1         USR:MPG.AMB_ORG_DAY_VIEW_RENDER (AGGREGATED)  0.919163
24                USR: PDOC NAVIGATOR DOC SET CLICK ()  0.117153
2     USR:PWR-OPEN CHART (DISCERNRPT/DISCERNPCTAB.DLL)  0.811958
27                    USR:ICU-IVIEW-ADDING A RESULT ()  0.141705
..                                                 ...       ...
167  USR:SRA SAANESTHESIA SAVE AND REFRESH RECORDS ...  0.329267
225                     USR:ORM.SEARCHFAVORITESITEM ()  0.001160
187    USR:PWR-REFRESH VIEW (REFRESHING TASK LIST TAB)  0.116975
237          USR:PHAMEDMGR.CALCULATE ORDER SCHEDULE ()  0.013083
166  USR:ORM.CONVERTTOINPATIENTMR-CONVERTORDER (NO ...  3.799895

     check_ag_in_prod?  tcap_atrt       dev      wt_dev  Unnamed: 14  \
0             0.343709   3.508434  3.174962  155.573154          NaN
1             0.910380   3.752565  2.833402  110.502665          NaN
24            0.117742   0.180805  0.063652   14.067189          NaN
2             0.830764   1.280765  0.468806   46.880623          NaN
27            0.140418   0.211395  0.069690   11.917034          NaN
..                 ...        ...       ...         ...          ...
167           0.329742   0.354951  0.025684    0.308203          NaN
225           0.001163   0.001140 -0.000020   -0.000243          NaN
187           0.120598   0.127342  0.010368    0.114046          NaN
237           0.012994   0.010500 -0.002583   -0.025831          NaN
166           3.834036   4.119056  0.319161    0.319161          NaN

     Unnamed: 15  Unnamed: 16  Unnamed: 17
0            NaN          NaN          NaN
1            NaN          NaN          NaN
24           NaN          NaN          NaN
2            NaN          NaN          NaN
27           NaN          NaN          NaN
..           ...          ...          ...
167          NaN          NaN          NaN
225          NaN          NaN          NaN
187          NaN          NaN          NaN
237          NaN          NaN          NaN
166          NaN          NaN          NaN

[92 rows x 18 columns]
✅ Saved selected rows to 'selected_rows.xlsx'

In [122]:

df.loc[picked].to_excel("selected_rows3.xlsx", index=False)

In [74]:
import pandas as pd
import numpy as np

# Load your Excel sheet
df = pd.read_excel("test_2.xlsx", sheet_name="cert_atrt")
col1 = "wt_dev"  # Only this column is now relevant

target1 = 1043.3678335398563  # Target sum for TOTAL_COUNT

# Convert to NumPy array for speed
a_vals = df[col1].values
n = len(df)

# Sort rows in descending order of contribution
indices = np.argsort(a_vals / target1)[::-1]

sum_a = 0
picked = []

for i in indices:
    if sum_a + a_vals[i] <= target1:
        picked.append(i)
        sum_a += a_vals[i]

        if abs(sum_a - target1) < 1e-3:
            break

# Output
if abs(sum_a - target1) < 1e-3:
    print(f"✅ Match found in rows: {picked}")
    print(f"Sum A: {sum_a:.4f}")
    print(df.loc[picked])
else:
    print(f"❌ No exact match found. Closest sum A: {sum_a:.4f}")

✅ Match found in rows: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 123, 194, 223]
Sum A: 1043.3669
      client domain                            additional_str_keys_uid  \
0    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ERM PMSEARCH WINDOW...
1    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.AMB_ORG_DAY_VIE...
2    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-OPEN CHART (DIS...
3    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ICU-IVIEW-GLOBAL SI...
4    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ARE.VERIFY RESULTS ...
5    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.RECOMMENDATIONS...
6    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.CHIEF_COMPLAINT...
7    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.TIMELINE_VS.O1 ...
8    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.DOCUMENTATION_G...
9    ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.DOCUMENTATION_H...
10   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PHAMEDMGRRETAIL.REF...
11   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: PN OPEN NOTE ()/GL...
12   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: DOCV: LOAD PN PROF...
13   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ORM.LOADORDERPROFIL...
14   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ARE.LOAD PATIENT AC...
15   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-CREATE VIEW (MA...
16   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.DOCUMENTATION_R...
17   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.OXYVENT.WF - LO...
18   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ERM PMACTION.TAB LO...
19   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-CREATE VIEW (OR...
20   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: DOCV: PREVIEW NOTE...
21   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: ICU PDOCPCFACTORY ...
22   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-OPEN CHART (ORD...
23   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.ALLERGY.O2 - LO...
24   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: PDOC NAVIGATOR DOC...
25   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-CREATE VIEW (PH...
26   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.AMB_ORG_DAY_VIE...
27   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ICU-IVIEW-ADDING A ...
28   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:REGISTRATION.LOADIN...
29   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR.PVINBOX.OPEN CO...
30   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PHAMEDMGRRETAIL.PAT...
31   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: CLINICAL NOTES: DI...
32   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.QUICKVISIT.O2 -...
33   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ORM.CHECKANDDISPLAY...
34   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-REFRESH VIEW (R...
35   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ICU-IVIEW-STARTING ...
36   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:PWR-REFRESH VIEW (R...
37   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:POWERFORMS.COMPLETE...
38   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: CLINICAL NOTES: LO...
39   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: PN SIGN NOTE ()/GL...
40   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.PROCEDURE.O2 - ...
41   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.HOME_MEDS.O1 - ...
42   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR: PN AUTOPOPULATE DA...
43   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.CUSTOM_COMP.O1 ...
44   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.MEDS.O1 - LOAD ...
45   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.VISITS.O1 - LOA...
46   ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ERM PMACTION SEARCH...
123  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ICU-IVIEW-STARTING ...
194  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:MPG.RCM.NOTES_LIST ...
223  ADHA_AE   PROD  TIMERNAME_SUBTIMERNAME:USR:ORM.ENHANCEDDETAILS...

        collection_time  TOTAL_TIME  TOTAL_COUNT   ATRT_AVG  \
0   2025-04-16 13:47:00  171.913284           49   3.508434
1   2025-04-16 13:47:00  146.350030           39   3.752565
2   2025-04-16 13:47:00  128.076467          100   1.280765
3   2025-04-16 13:47:00   89.423026           53   1.687227
4   2025-04-16 13:47:00   59.865275           28   2.138046
5   2025-04-16 13:47:00   79.114947           24   3.296456
6   2025-04-16 13:47:00   49.284514           71   0.694148
7   2025-04-16 13:47:00  117.078018            3  39.026006
8   2025-04-16 13:47:00   33.964320            9   3.773813
9   2025-04-16 13:47:00   46.648681           41   1.137773
10  2025-04-16 13:47:00   44.343832            8   5.542979
11  2025-04-16 13:47:00   32.404021            5   6.480804
12  2025-04-16 13:47:00   23.900340            6   3.983390
13  2025-04-16 13:47:00   69.531678          116   0.599411
14  2025-04-16 13:47:00   42.829838           43   0.996043
15  2025-04-16 13:47:00   38.010569           36   1.055849
16  2025-04-16 13:47:00   38.683515           33   1.172228
17  2025-04-16 13:47:00   27.990586            2  13.995293
18  2025-04-16 13:47:00   30.591846           12   2.549320
19  2025-04-16 13:47:00   43.052290           27   1.594529
20  2025-04-16 13:47:00   53.850425           89   0.605061
21  2025-04-16 13:47:00   48.131450           76   0.633309
22  2025-04-16 13:47:00   37.782612           12   3.148551
23  2025-04-16 13:47:00   30.985368           50   0.619707
24  2025-04-16 13:47:00   39.957892          221   0.180805
25  2025-04-16 13:47:00   37.116232           41   0.905274
26  2025-04-16 13:47:00   21.832005           41   0.532488
27  2025-04-16 13:47:00   36.148561          171   0.211395
28  2025-04-16 13:47:00   27.386725           13   2.106671
29  2025-04-16 13:47:00   18.853690           35   0.538677
30  2025-04-16 13:47:00   58.769141           14   4.197796
31  2025-04-16 13:47:00   13.253011            1  13.253011
32  2025-04-16 13:47:00   11.526912           10   1.152691
33  2025-04-16 13:47:00   12.771286           17   0.751252
34  2025-04-16 13:47:00   12.203195            6   2.033866
35  2025-04-16 13:47:00   28.638274          114   0.251213
36  2025-04-16 13:47:00   18.773230           21   0.893963
37  2025-04-16 13:47:00   44.703609           46   0.971818
38  2025-04-16 13:47:00   27.013287           39   0.692648
39  2025-04-16 13:47:00   15.468369           15   1.031225
40  2025-04-16 13:47:00   10.184932           11   0.925903
41  2025-04-16 13:47:00   10.432032            6   1.738672
42  2025-04-16 13:47:00   12.652083            4   3.163021
43  2025-04-16 13:47:00    9.979066            9   1.108785
44  2025-04-16 13:47:00   10.774433            8   1.346804
45  2025-04-16 13:47:00    8.985344            7   1.283621
46  2025-04-16 13:47:00   23.467659           10   2.346766
123 2025-04-16 13:47:00    2.628855            3   0.876285
194 2025-04-16 13:47:00    0.346170            2   0.173085
223 2025-04-16 13:47:00    0.048387           58   0.000834

                                                    ts  \
0                      USR:ERM PMSEARCH WINDOW LOAD ()
1         USR:MPG.AMB_ORG_DAY_VIEW_RENDER (AGGREGATED)
2     USR:PWR-OPEN CHART (DISCERNRPT/DISCERNPCTAB.DLL)
3              USR:ICU-IVIEW-GLOBAL SIGNING RESULTS ()
4                            USR:ARE.VERIFY RESULTS ()
5    USR:MPG.RECOMMENDATIONS.O2 - LOAD COMPONENT (A...
6    USR:MPG.CHIEF_COMPLAINT.O1 - LOAD COMPONENT (A...
7    USR:MPG.TIMELINE_VS.O1 - LOAD COMPONENT (AGGRE...
8    USR:MPG.DOCUMENTATION_GEN.O1_LOAD_COMPONENT (A...
9    USR:MPG.DOCUMENTATION_HPI.O1 - LOAD COMPONENT ...
10                       USR:PHAMEDMGRRETAIL.REFILL ()
11                                USR: PN OPEN NOTE ()
12                       USR: DOCV: LOAD PN PROFILE ()
13                         USR:ORM.LOADORDERPROFILE ()
14                   USR:ARE.LOAD PATIENT ACCESSION ()
15                     USR:PWR-CREATE VIEW (MAR/PVMAR)
16   USR:MPG.DOCUMENTATION_ROS.O1 - LOAD COMPONENT ...
17    USR:MPG.OXYVENT.WF - LOAD COMPONENT (AGGREGATED)
18                        USR:ERM PMACTION.TAB LOAD ()
19       USR:PWR-CREATE VIEW (ORDERMEDLIST/PVORDERPOE)
20                          USR: DOCV: PREVIEW NOTE ()
21   USR: ICU PDOCPCFACTORY - OPENING A NEW PATIENT...
22        USR:PWR-OPEN CHART (ORDERMEDLIST/PVORDERPOE)
23    USR:MPG.ALLERGY.O2 - LOAD COMPONENT (AGGREGATED)
24                USR: PDOC NAVIGATOR DOC SET CLICK ()
25             USR:PWR-CREATE VIEW (PHYSDOC/PDOCSHELL)
26          USR:MPG.AMB_ORG_DAY_VIEW_LOAD (AGGREGATED)
27                    USR:ICU-IVIEW-ADDING A RESULT ()
28            USR:REGISTRATION.LOADING CONVERSATION ()
29               USR:PWR.PVINBOX.OPEN CONFIGURATION ()
30                  USR:PHAMEDMGRRETAIL.PATIENTLOAD ()
31               USR: CLINICAL NOTES: DISPLAY IMAGE ()
32   USR:MPG.QUICKVISIT.O2 - LOAD COMPONENT (AGGREG...
33              USR:ORM.CHECKANDDISPLAYINTERACTIONS ()
34   USR:PWR-REFRESH VIEW (REFRESHING MESSAGE CENTE...
35   USR:ICU-IVIEW-STARTING DOCUMENTATION ON A SING...
36           USR:PWR-REFRESH VIEW (REFRESHING MAR TAB)
37   USR:POWERFORMS.COMPLETE DOCUMENTATION (POWERFO...
38                   USR: CLINICAL NOTES: LOAD NOTE ()
39                                USR: PN SIGN NOTE ()
40   USR:MPG.PROCEDURE.O2 - LOAD COMPONENT (AGGREGA...
41   USR:MPG.HOME_MEDS.O1 - LOAD COMPONENT (AGGREGA...
42                        USR: PN AUTOPOPULATE DATA ()
43   USR:MPG.CUSTOM_COMP.O1 - LOAD COMPONENT (AGGRE...
44       USR:MPG.MEDS.O1 - LOAD COMPONENT (AGGREGATED)
45     USR:MPG.VISITS.O1 - LOAD COMPONENT (AGGREGATED)
46    USR:ERM PMACTION SEARCH TO CONVERSATION READY ()
123  USR:ICU-IVIEW-STARTING DOCUMENTATION FOR A TIM...
194  USR:MPG.RCM.NOTES_LIST - LOAD COMPONENT (AGGRE...
223               USR:ORM.ENHANCEDDETAILSTABCREATED ()

                                       check _in_prod?        ga  tcap_atrt  \
0                      USR:ERM PMSEARCH WINDOW LOAD ()  0.333472   3.508434
1         USR:MPG.AMB_ORG_DAY_VIEW_RENDER (AGGREGATED)  0.919163   3.752565
2     USR:PWR-OPEN CHART (DISCERNRPT/DISCERNPCTAB.DLL)  0.811958   1.280765
3              USR:ICU-IVIEW-GLOBAL SIGNING RESULTS ()  0.863276   1.687227
4                            USR:ARE.VERIFY RESULTS ()  0.612450   2.138046
5    USR:MPG.RECOMMENDATIONS.O2 - LOAD COMPONENT (A...  1.721266   3.296456
6    USR:MPG.CHIEF_COMPLAINT.O1 - LOAD COMPONENT (A...  0.168014   0.694148
7    USR:MPG.TIMELINE_VS.O1 - LOAD COMPONENT (AGGRE...  0.376702  10.000000
8    USR:MPG.DOCUMENTATION_GEN.O1_LOAD_COMPONENT (A...  0.606619   3.773813
9    USR:MPG.DOCUMENTATION_HPI.O1 - LOAD COMPONENT ...  0.540585   1.137773
10                       USR:PHAMEDMGRRETAIL.REFILL ()  2.522390   5.542979
11                                USR: PN OPEN NOTE ()  1.694163   6.480804
12                       USR: DOCV: LOAD PN PROFILE ()  0.244466   3.983390
13                         USR:ORM.LOADORDERPROFILE ()  0.423913   0.599411
14                   USR:ARE.LOAD PATIENT ACCESSION ()  0.525983   0.996043
15                     USR:PWR-CREATE VIEW (MAR/PVMAR)  0.518885   1.055849
16   USR:MPG.DOCUMENTATION_ROS.O1 - LOAD COMPONENT ...  0.588612   1.172228
17    USR:MPG.OXYVENT.WF - LOAD COMPONENT (AGGREGATED)  0.705995  10.000000
18                        USR:ERM PMACTION.TAB LOAD ()  1.027669   2.549320
19       USR:PWR-CREATE VIEW (ORDERMEDLIST/PVORDERPOE)  0.953914   1.594529
20                          USR: DOCV: PREVIEW NOTE ()  0.414784   0.605061
21   USR: ICU PDOCPCFACTORY - OPENING A NEW PATIENT...  0.423049   0.633309
22        USR:PWR-OPEN CHART (ORDERMEDLIST/PVORDERPOE)  1.947038   3.148551
23    USR:MPG.ALLERGY.O2 - LOAD COMPONENT (AGGREGATED)  0.333174   0.619707
24                USR: PDOC NAVIGATOR DOC SET CLICK ()  0.117153   0.180805
25             USR:PWR-CREATE VIEW (PHYSDOC/PDOCSHELL)  0.589861   0.905274
26          USR:MPG.AMB_ORG_DAY_VIEW_LOAD (AGGREGATED)  0.223820   0.532488
27                    USR:ICU-IVIEW-ADDING A RESULT ()  0.141705   0.211395
28            USR:REGISTRATION.LOADING CONVERSATION ()  1.289641   2.106671
29               USR:PWR.PVINBOX.OPEN CONFIGURATION ()  0.242644   0.538677
30                  USR:PHAMEDMGRRETAIL.PATIENTLOAD ()  3.458459   4.197796
31               USR: CLINICAL NOTES: DISPLAY IMAGE ()  0.083404  10.000000
32   USR:MPG.QUICKVISIT.O2 - LOAD COMPONENT (AGGREG...  0.167077   1.152691
33              USR:ORM.CHECKANDDISPLAYINTERACTIONS ()  0.182520   0.751252
34   USR:PWR-REFRESH VIEW (REFRESHING MESSAGE CENTE...  0.432166   2.033866
35   USR:ICU-IVIEW-STARTING DOCUMENTATION ON A SING...  0.167108   0.251213
36           USR:PWR-REFRESH VIEW (REFRESHING MAR TAB)  0.491944   0.893963
37   USR:POWERFORMS.COMPLETE DOCUMENTATION (POWERFO...  0.788446   0.971818
38                   USR: CLINICAL NOTES: LOAD NOTE ()  0.481347   0.692648
39                                USR: PN SIGN NOTE ()  0.485273   1.031225
40   USR:MPG.PROCEDURE.O2 - LOAD COMPONENT (AGGREGA...  0.184578   0.925903
41   USR:MPG.HOME_MEDS.O1 - LOAD COMPONENT (AGGREGA...  0.388324   1.738672
42                        USR: PN AUTOPOPULATE DATA ()  1.149422   3.163021
43   USR:MPG.CUSTOM_COMP.O1 - LOAD COMPONENT (AGGRE...  0.230847   1.108785
44       USR:MPG.MEDS.O1 - LOAD COMPONENT (AGGREGATED)  0.366089   1.346804
45     USR:MPG.VISITS.O1 - LOAD COMPONENT (AGGREGATED)  0.179872   1.283621
46    USR:ERM PMACTION SEARCH TO CONVERSATION READY ()  1.589790   2.346766
123  USR:ICU-IVIEW-STARTING DOCUMENTATION FOR A TIM...  0.470941   0.876285
194  USR:MPG.RCM.NOTES_LIST - LOAD COMPONENT (AGGRE...  0.129353   0.173085
223               USR:ORM.ENHANCEDDETAILSTABCREATED ()  0.000831   0.000834

          dev      wt_dev  Unnamed: 13  Unnamed: 14  Unnamed: 15
0    3.174962  155.573154          NaN          NaN          NaN
1    2.833402  110.502665          NaN          NaN          NaN
2    0.468806   46.880623          NaN          NaN          NaN
3    0.823951   43.669396          NaN          NaN          NaN
4    1.525595   42.716664          NaN          NaN          NaN
5    1.575190   37.804571          NaN          NaN          NaN
6    0.526134   37.355522          NaN          NaN          NaN
7    9.623298   28.869894          NaN          NaN          NaN
8    3.167195   28.504752          NaN          NaN          NaN
9    0.597188   24.484695          NaN          NaN          NaN
10   3.020589   24.164714          NaN          NaN          NaN
11   4.786641   23.933205          NaN          NaN          NaN
12   3.738924   22.433545          NaN          NaN          NaN
13   0.175498   20.357802          NaN          NaN          NaN
14   0.470060   20.212589          NaN          NaN          NaN
15   0.536965   19.330722          NaN          NaN          NaN
16   0.583616   19.259334          NaN          NaN          NaN
17   9.294005   18.588011          NaN          NaN          NaN
18   1.521652   18.259821          NaN          NaN          NaN
19   0.640615   17.296606          NaN          NaN          NaN
20   0.190277   16.934634          NaN          NaN          NaN
21   0.210259   15.979708          NaN          NaN          NaN
22   1.201514   14.418162          NaN          NaN          NaN
23   0.286533   14.326646          NaN          NaN          NaN
24   0.063652   14.067189          NaN          NaN          NaN
25   0.315413   12.931926          NaN          NaN          NaN
26   0.308668   12.655372          NaN          NaN          NaN
27   0.069690   11.917034          NaN          NaN          NaN
28   0.817030   10.621396          NaN          NaN          NaN
29   0.296033   10.361163          NaN          NaN          NaN
30   0.739337   10.350714          NaN          NaN          NaN
31   9.916596    9.916596          NaN          NaN          NaN
32   0.985614    9.856143          NaN          NaN          NaN
33   0.568733    9.668455          NaN          NaN          NaN
34   1.601700    9.610199          NaN          NaN          NaN
35   0.084105    9.587927          NaN          NaN          NaN
36   0.402020    8.442415          NaN          NaN          NaN
37   0.183371    8.435071          NaN          NaN          NaN
38   0.211301    8.240735          NaN          NaN          NaN
39   0.545952    8.189277          NaN          NaN          NaN
40   0.741324    8.154569          NaN          NaN          NaN
41   1.350348    8.102087          NaN          NaN          NaN
42   2.013598    8.054394          NaN          NaN          NaN
43   0.877938    7.901441          NaN          NaN          NaN
44   0.980715    7.845723          NaN          NaN          NaN
45   1.103749    7.726240          NaN          NaN          NaN
46   0.756976    7.569762          NaN          NaN          NaN
123  0.405344    1.216031          NaN          NaN          NaN
194  0.043732    0.087464          NaN          NaN          NaN
223  0.000003    0.000180          NaN          NaN          NaN

In [116]:
df.loc[picked].wt_dev.sum()

1043.349266462844

In [441]:
import asyncio
from edge_tts import Communicate

async def tts_api(text: str, out_mp3: str, voice: str = "ar-EG-SalmaNeural"):
    comm = Communicate(text, voice)
    await comm.save(out_mp3)

if __name__ == "__main__":
    text     = "مرحبا كيف حالك؟"
    out_file = "hello_in_arabic.mp3"
    asyncio.run(tts_api(text, out_file))

ModuleNotFoundError: No module named 'aiohttp'

In [159]:
import pandas as pd

# 1) Load the original verb_counts data
df = pd.read_excel('verb_counts_final_completed.xlsx')

# 2) Normalization helper
def normalize_for_qutrub(text):
    return (text
            .replace("ٱ", "اِ")  # replace wasla-alif with alif+kasra
            .replace("ٰ", "")    # remove dagger-alif
            .replace("ْ", "")     # remove damma
            .replace("ٓ", "")
           )

# 3) Prepare new column
api_results = []

for idx, row in df.iterrows():
    # Use your corrected form if available, otherwise the raw Arabic
    verb = row.get('Corrected_3MS_Past_Final', row.get('Arabic', ''))
    cleaned = normalize_for_qutrub(verb)
    
    raw_qutrub = get_qutrub_conjugation_cached(cleaned)
    result = raw_qutrub.get('result')
    
    if isinstance(result, dict):
        q9_1 = result.get('9', {}).get('1')
        api_results.append(q9_1 or 'no data found')
    else:
        api_results.append('no data found')

# 4) Append to DataFrame and save
df['API_9_1'] = api_results

output_path = 'verb_counts_with_api_final2.xlsx'
df.to_excel(output_path, index=False)


output_path

'verb_counts_with_api.xlsx'

In [85]:
"أَنْزَلَ".replace("ْ", "")

'أَنزَلَ'

In [389]:
api_output = get_qutrub_conjugation(remove_dagger_alif_and_wasla("بَشَّرَ"))#["result"]["9"]#["1"]
api_output

{'result': {'0': {'0': 'الضمائر',
   '1': 'الماضي المعلوم',
   '2': 'المضارع المعلوم',
   '3': 'المضارع المجزوم',
   '4': 'المضارع المنصوب',
   '5': 'المضارع المؤكد الثقيل',
   '6': 'الأمر',
   '7': 'الأمر المؤكد'},
  '1': {'0': 'أنا',
   '1': 'بَشَّرْتُ',
   '2': 'أُبَشِّرُ',
   '3': 'أُبَشِّرْ',
   '4': 'أُبَشِّرَ',
   '5': 'أُبَشِّرَنَّ',
   '6': '',
   '7': ''},
  '10': {'0': 'هي',
   '1': 'بَشَّرَتْ',
   '2': 'تُبَشِّرُ',
   '3': 'تُبَشِّرْ',
   '4': 'تُبَشِّرَ',
   '5': 'تُبَشِّرَنَّ',
   '6': '',
   '7': ''},
  '11': {'0': 'هما',
   '1': 'بَشَّرَا',
   '2': 'يُبَشِّرَانِ',
   '3': 'يُبَشِّرَا',
   '4': 'يُبَشِّرَا',
   '5': 'يُبَشِّرَانِّ',
   '6': '',
   '7': ''},
  '12': {'0': 'هما مؤ',
   '1': 'بَشَّرَتَا',
   '2': 'تُبَشِّرَانِ',
   '3': 'تُبَشِّرَا',
   '4': 'تُبَشِّرَا',
   '5': 'تُبَشِّرَانِّ',
   '6': '',
   '7': ''},
  '13': {'0': 'هم',
   '1': 'بَشَّرُوا',
   '2': 'يُبَشِّرُونَ',
   '3': 'يُبَشِّرُوا',
   '4': 'يُبَشِّرُوا',
   '5': 'يُبَشِّرُنَّ',
   '6': '',
   '7': ''},
  '14': {'0': 'هن',
   '1': 'بَشَّرْنَ',
   '2': 'يُبَشِّرْنَ',
   '3': 'يُبَشِّرْنَ',
   '4': 'يُبَشِّرْنَ',
   '5': 'يُبَشِّرْنَانِّ',
   '6': '',
   '7': ''},
  '2': {'0': 'نحن',
   '1': 'بَشَّرْنَا',
   '2': 'نُبَشِّرُ',
   '3': 'نُبَشِّرْ',
   '4': 'نُبَشِّرَ',
   '5': 'نُبَشِّرَنَّ',
   '6': '',
   '7': ''},
  '3': {'0': 'أنت',
   '1': 'بَشَّرْتَ',
   '2': 'تُبَشِّرُ',
   '3': 'تُبَشِّرْ',
   '4': 'تُبَشِّرَ',
   '5': 'تُبَشِّرَنَّ',
   '6': 'بَشِّرْ',
   '7': 'بَشِّرَنَّ'},
  '4': {'0': 'أنتِ',
   '1': 'بَشَّرْتِ',
   '2': 'تُبَشِّرِينَ',
   '3': 'تُبَشِّرِي',
   '4': 'تُبَشِّرِي',
   '5': 'تُبَشِّرِنَّ',
   '6': 'بَشِّرِي',
   '7': 'بَشِّرِنَّ'},
  '5': {'0': 'أنتما',
   '1': 'بَشَّرْتُمَا',
   '2': 'تُبَشِّرَانِ',
   '3': 'تُبَشِّرَا',
   '4': 'تُبَشِّرَا',
   '5': 'تُبَشِّرَانِّ',
   '6': 'بَشِّرَا',
   '7': 'بَشِّرَانِّ'},
  '6': {'0': 'أنتما مؤ',
   '1': 'بَشَّرْتُمَا',
   '2': 'تُبَشِّرَانِ',
   '3': 'تُبَشِّرَا',
   '4': 'تُبَشِّرَا',
   '5': 'تُبَشِّرَانِّ',
   '6': 'بَشِّرَا',
   '7': 'بَشِّرَانِّ'},
  '7': {'0': 'أنتم',
   '1': 'بَشَّرْتُم',
   '2': 'تُبَشِّرُونَ',
   '3': 'تُبَشِّرُوا',
   '4': 'تُبَشِّرُوا',
   '5': 'تُبَشِّرُنَّ',
   '6': 'بَشِّرُوا',
   '7': 'بَشِّرُنَّ'},
  '8': {'0': 'أنتن',
   '1': 'بَشَّرْتُنَّ',
   '2': 'تُبَشِّرْنَ',
   '3': 'تُبَشِّرْنَ',
   '4': 'تُبَشِّرْنَ',
   '5': 'تُبَشِّرْنَانِّ',
   '6': 'بَشِّرْنَ',
   '7': 'بَشِّرْنَانِّ'},
  '9': {'0': 'هو',
   '1': 'بَشَّرَ',
   '2': 'يُبَشِّرُ',
   '3': 'يُبَشِّرْ',
   '4': 'يُبَشِّرَ',
   '5': 'يُبَشِّرَنَّ',
   '6': '',
   '7': ''}},
 'suggest': [{'future': 'يُبَشِّرُ',
   'haraka': 'فتحة',
   'transitive': False,
   'verb': 'بَشَّرَ'},
  {'future': 'يَبْشَرُ',
   'haraka': 'فتحة',
   'transitive': False,
   'verb': 'بَشَرَ'},
  {'future': 'يَبْشَرُ',
   'haraka': 'فتحة',
   'transitive': False,
   'verb': 'بَشُرَ'},
  {'future': 'يَبْشَرُ',
   'haraka': 'فتحة',
   'transitive': False,
   'verb': 'بَشِرَ'},
  {'future': 'يُبَاشِرُ',
   'haraka': 'فتحة',
   'transitive': True,
   'verb': 'باشَرَ'},
  {'future': 'يُبْشِرُ',
   'haraka': 'فتحة',
   'transitive': False,
   'verb': 'أَبْشَرَ'}],
 'verb_info': '"الفعل \n        بَشَّرَ - يُبَشِّرُ فعل رباعي لازم صحيح مضعف [في قاعدة البيانات]'}

In [407]:
def generate_ordered_sentences(api_output):
    res = api_output["result"]
    # Define the exact order of keys for the pronouns
    pronoun_keys = ['9','11','13','10','12','14','3','5','7','4','6','8','1','2']
    # Map each key to its pronoun label
    pronouns = [res[k]['0'] for k in pronoun_keys]

    pronouns = [
    'أَنْتُنَّ' if res[k]['0'].replace(" مؤ", "") == 'أنتن'
    else res[k]['0'].replace(" مؤ", "")
    for k in pronoun_keys]

    # Extract past and present stems
    past    = [res[k]['1'] for k in pronoun_keys]
    present = [res[k]['2'] for k in pronoun_keys]


    def join(ps, fs):
        return ", ".join(f"{p} {f}" for p, f in zip(ps, fs))

    return {
        "Past Tense":         join(pronouns, past),
        "Present Tense":      join(pronouns, present)
    }

# Example usage with your API output dict:


sentences = generate_ordered_sentences(api_output)
for tense, line in sentences.items():
    print(f"{tense}: {line}")

Past Tense: هو بَشَّرَ, هما بَشَّرَا, هم بَشَّرُوا, هي بَشَّرَتْ, هما مؤ بَشَّرَتَا, هن بَشَّرْنَ, أنت بَشَّرْتَ, أنتما بَشَّرْتُمَا, أنتم بَشَّرْتُم, أنتِ بَشَّرْتِ, أنتما مؤ بَشَّرْتُمَا, أَنْتُنَّ بَشَّرْتُنَّ, أنا بَشَّرْتُ, نحن بَشَّرْنَا
Present Tense: هو يُبَشِّرُ, هما يُبَشِّرَانِ, هم يُبَشِّرُونَ, هي تُبَشِّرُ, هما مؤ تُبَشِّرَانِ, هن يُبَشِّرْنَ, أنت تُبَشِّرُ, أنتما تُبَشِّرَانِ, أنتم تُبَشِّرُونَ, أنتِ تُبَشِّرِينَ, أنتما مؤ تُبَشِّرَانِ, أَنْتُنَّ تُبَشِّرْنَ, أنا أُبَشِّرُ, نحن نُبَشِّرُ

In [409]:
from pathlib import Path
from openai import OpenAI


import os
os.environ["OPENAI_API_KEY"] = "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"



def generate_ordered_sentences(api_output):
    res = api_output["result"]
    # exact pronoun order
    pronoun_keys = ['9','11','13','10','12','14','3','5','7','4','6','8','1','2']
    # clean pronouns, handle أنتُنَّ
    pronouns = [
        'أَنْتُنَّ' if res[k]['0'].replace(" مؤ", "") == 'أنتن'
        else res[k]['0'].replace(" مؤ", "")
        for k in pronoun_keys
    ]
    past    = [res[k]['1'] for k in pronoun_keys]
    present = [res[k]['2'] for k in pronoun_keys]

    def join(ps, fs):
        return ", ".join(f"{p} {f}" for p, f in zip(ps, fs))

    return join(pronouns, past), join(pronouns, present)


# derive root/verb for filename
root = api_output['suggest'][0]['verb']

# generate lines
past_line, present_line = generate_ordered_sentences(api_output)

client = OpenAI()

# save past tense audio
past_file = Path(f"{root}_past.mp3")
with client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="onyx",
    input=past_line,
    instructions="Speak clearly in Arabic."
) as resp:
    resp.stream_to_file(past_file)

# save present tense audio
present_file = Path(f"{root}_present.mp3")
with client.audio.speech.with_streaming_response.create(
    model="tts-1",
    voice="onyx",
    input=present_line,
    instructions="Speak clearly in Arabic."
) as resp:
    resp.stream_to_file(present_file)

print(f"Generated: {past_file}, {present_file}")

ModuleNotFoundError: No module named 'aiohttp'

In [1]:
from camel_tools.morphology.database import MorphologyDB
from camel_tools.morphology.analyzer import Analyzer
import pandas as pd

# Load the built-in CAMeL Tools morphology database
db = MorphologyDB.builtin_db()

# Initialize the analyzer
analyzer = Analyzer(db)

# Example word to analyze
word = 'يَحْزُن'

# Perform analysis
analyses = analyzer.analyze(word)

# Convert analyses to a DataFrame for easy viewing
df = pd.DataFrame(analyses)

df.head()

ModuleNotFoundError: No module named 'camel_tools'

In [6]:
import sys
print(sys.version)

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]

In [8]:
import sys
print(sys.version)
print(sys.executable)

from camel_tools.morphology.database import MorphologyDB
from camel_tools.morphology.analyzer import Analyzer

print("camel-tools installed successfully")

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]
C:\Users\Abrar\anaconda3\python.exe

ModuleNotFoundError: No module named 'camel_tools'

In [9]:
conda create -n camel39 python=3.9 -y

Jupyter detected...
Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
    current version: 25.5.1
    latest version: 25.11.1

Please update conda by running

    $ conda update -n base -c defaults conda

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Abrar\anaconda3\envs\camel39

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-h2bbff1b_6
  ca-certificates    pkgs/main/win-64::ca-certificates-2025.12.2-haa95532_0
  expat              pkgs/main/win-64::expat-2.7.3-h885b0b7_4
  libexpat           pkgs/main/win-64::libexpat-2.7.3-h885b0b7_4
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1
  libzlib            pkgs/main/win-64::libzlib-1.3.1-h02ab6af_0
  openssl            pkgs/main/win-64::openssl-3.0.18-h543e019_0
  pip                pkgs/main/noarch::pip-25.3-pyhc872135_0
  python             pkgs/main/win-64::python-3.9.25-h716150d_1
  setuptools         pkgs/main/win-64::setuptools-80.9.0-py39haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.51.1-hda9a48d_0
  tk                 pkgs/main/win-64::tk-8.6.15-hf199647_0
  tzdata             pkgs/main/noarch::tzdata-2025b-h04d1e81_0
  ucrt               pkgs/main/win-64::ucrt-10.0.22621.0-haa95532_0
  vc                 pkgs/main/win-64::vc-14.3-h2df5915_10
  vc14_runtime       pkgs/main/win-64::vc14_runtime-14.44.35208-h4927774_10
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.44.35208-ha6b5a95_10
  wheel              pkgs/main/win-64::wheel-0.45.1-py39haa95532_0
  xz                 pkgs/main/win-64::xz-5.6.4-h4754444_1
  zlib               pkgs/main/win-64::zlib-1.3.1-h02ab6af_0



Downloading and Extracting Packages: ...working... done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate camel39
#
# To deactivate an active environment, use
#
#     $ conda deactivate

In [11]:
python --version

NameError: name 'python' is not defined

In [10]:
conda activate camel39

Note: you may need to restart the kernel to use updated packages.

In [7]:
import sys
print(sys.executable)

C:\Users\Abrar\anaconda3\python.exe

In [345]:
df_morph[df_morph["VERB_MAIN"] !='NOT VERB']

,Surah,Ayah,WordIndex,SubIndex,TAG,FORM,Root,Lemma,Arabic,FEATURES,VERB_MAIN,Person,Gender,Number,TAG_Explanation,count,meaning,3MSAP_root
23,1,5,2,1,V,naEobudu,Ebd,Eabada,عَبَدَ,STEM|POS:V|IMPF|LEM:Eabada|ROOT:Ebd|1P,عَبَدَ,first person,None,plural,Verb,122.0,we worship,عَبَدَ
26,1,5,4,1,V,nasotaEiynu,Ewn,{sotaEiynu,ٱسْتَعِينُ,STEM|POS:V|IMPF|(X)|LEM:{sotaEiynu|ROOT:Ewn|1P,ٱسْتَعِينُ,first person,None,plural,Verb,4.0,we ask for help,اِسْتَعَانَ
27,1,6,1,1,V,{hodi,hdy,hadaY,هَدَى,STEM|POS:V|IMPV|LEM:hadaY|ROOT:hdy|2MS,هَدَى,second person,masculine,singular,Verb,144.0,Guide us,هَدَى
35,1,7,3,1,V,>anoEamo,nEm,>anoEama,أَنْعَمَ,STEM|POS:V|PERF|(IV)|LEM:>anoEama|ROOT:nEm|2MS,أَنْعَمَ,second person,masculine,singular,Verb,17.0,You have bestowed (Your) Favors,أَنْعَمَ
61,2,3,2,1,V,yu&ominu,Amn,'aAmana,ءَامَنَ,STEM|POS:V|IMPF|(IV)|LEM:'aAmana|ROOT:Amn|3MP,ءَامَنَ,third person,masculine,plural,Verb,537.0,believe,آمَنَ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128174,113,3,5,1,V,waqaba,wqb,waqaba,وَقَبَ,STEM|POS:V|PERF|LEM:waqaba|ROOT:wqb|3MS,وَقَبَ,third person,masculine,singular,Verb,1.0,it spreads,وَقَبَ
128188,113,5,5,1,V,Hasada,Hsd,Hasada,حَسَدَ,STEM|POS:V|PERF|LEM:Hasada|ROOT:Hsd|3MS,حَسَدَ,third person,masculine,singular,Verb,3.0,are they jealous,حَسَدَ
128189,114,1,1,1,V,qulo,qwl,qaAla,قَالَ,STEM|POS:V|IMPV|LEM:qaAla|ROOT:qwl|2MS,قَالَ,second person,masculine,singular,Verb,1618.0,say,قَالَ
128190,114,1,2,1,V,>aEuw*u,Ew*,Eu*o,عُذْ,STEM|POS:V|IMPF|LEM:Eu*o|ROOT:Ew*|1S,عُذْ,first person,None,singular,Verb,10.0,I seek refuge,عَاذَ
128208,114,5,2,1,V,yuwasowisu,wsws,wasowasa,وَسْوَسَ,STEM|POS:V|IMPF|LEM:wasowasa|ROOT:wsws|3MS,وَسْوَسَ,third person,masculine,singular,Verb,4.0,Then whispered,سَاسَ

In [291]:
import time

def fetch_meaning(row):
    # Call the API once per verse
    mapping = get_quran_word_api_data(row["verse_key"])
    # WordIndex in your df matches the ‘position’ key in the mapping
    pos = int(row["WordIndex"])
    # Return the translation (or empty string if missing)
    return mapping.get(pos, "")

# Throttle the calls so we don’t hammer the API
meanings = []
for i, row in df.iterrows():
    meaning = fetch_meaning(row)
    meanings.append(meaning)
    print(f"{row['Arabic']} @ {row['verse_key']}[{row['WordIndex']}] → {meaning}")
    time.sleep(0.2)

df["meaning"] = meanings

# Save out
out_path = "verbs_with_meanings.xlsx"
df.to_excel(out_path, index=False)
print(f"✅ Wrote {len(df)} rows (with meanings) to {out_path}")

قَالَ @ 2:8[4] → say
كَانَ @ 2:10[11] → they used to
ءَامَنَ @ 2:3[2] → believe
عَلِمَ @ 2:13[19] → they know
جَعَلَ @ 2:19[9] → They put
كَفَرَ @ 2:6[3] → disbelieve[d]
جَآءَ @ 2:71[19] → you have come
عَمِلَ @ 2:25[4] → and do
رَءَا @ 2:55[8] → we see
آتَى @ 2:43[3] → and give
أَتَى @ 2:23[9] → then produce
شَآءَ @ 2:20[15] → had willed
خَلَقَ @ 2:21[6] → created you
أَنزَلَ @ 2:4[4] → (is) sent down
كَذَّبَ @ 2:39[3] → and deny
دَعَا @ 2:23[13] → and call
ٱتَّقَىٰ @ 2:21[11] → become righteous
هَدَى @ 1:6[1] → Guide us
أَرَادَ @ 2:26[25] → (did) intend
ٱتَّبَعَ @ 2:102[1] → And they followed
أَرْسَلَ @ 2:119[2] → [We] have sent you
أَخَذَ @ 2:48[14] → will be taken
ٱتَّخَذَ @ 2:51[7] → you took
عَبَدَ @ 1:5[2] → we worship
ظَلَمَ @ 2:54[7] → [you] have wronged
سَأَلَ @ 2:61[36] → you have asked (for)
وَجَدَ @ 2:96[1] → And surely you will find them
أَخْرَجَ @ 2:22[12] → then brought forth
أَكَلَ @ 2:35[7] → and [you both] eat
لَّيْسَ @ 2:113[3] → Not
فَعَلَ @ 2:24[3] → you do
نَّظَرَ @ 2:50[10] → (were) looking
ذَكَرَ @ 2:40[3] → Remember
خَافَ @ 2:182[2] → fears
قَتَلَ @ 2:54[14] → and kill
رَجَعَ @ 2:18[6] → [they] will not return
سَمِعَ @ 2:75[9] → (who used to) hear
تَوَلَّىٰ @ 2:64[2] → you turned away
أَمَرَ @ 2:27[10] → has ordered
دَخَلَ @ 2:58[3] → Enter
جَزَىٰ @ 2:48[4] → avail
أَطَاعَ @ 2:285[23] → and we obeyed
أَوْحَىٰٓ @ 3:44[5] → We reveal it
أَلْقَىٰٓ @ 2:195[6] → throw (yourselves)
أَشْرَكَ @ 2:96[8] → associate[d] partners (with Allah)
وَعَدَ @ 2:268[2] → promises you
أَنفَقَ @ 2:3[8] → they spend
غَفَرَ @ 2:58[16] → We will forgive
أَحْبَبْ @ 2:165[9] → They love them
أَصَابَ @ 2:156[3] → strikes them
أَضَلَّ @ 2:26[29] → He lets go astray
تَابَ @ 2:37[6] → So (his Lord) turned
نَزَّلَ @ 2:23[6] → We have revealed
كَسَبَ @ 2:79[24] → they earn
رَزَقَ @ 2:3[7] → We have provided them
تَلَىٰ @ 2:44[7] → [you] recite
نَصَرَ @ 2:48[19] → will be helped
قَضَىٰٓ @ 2:117[5] → He decrees
صَبَرَ @ 2:61[5] → we endure
جَرَيْ @ 2:25[9] → flow
مَسَّ @ 2:80[3] → will touch us
ضَرَبَ @ 2:26[6] → set forth
أَقَامَ @ 2:3[4] → and establish
قَٰتَلَ @ 2:190[1] → And fight
ضَلَّ @ 2:108[16] → he went astray (from)
خَرَجَ @ 2:74[23] → so comes out
بَعَثَ @ 2:56[2] → We revived you
تَذَكَّرَ @ 2:221[39] → take heed
أَحْيَا @ 2:28[6] → then He gave you life
أَهْلَكَ @ 2:205[8] → and destroys
ٱفْتَرَىٰ @ 3:24[15] → inventing
كَتَبَ @ 2:79[3] → write
عَقَلُ @ 2:44[10] → you use reason
زَادَ @ 2:10[4] → so has increased them
ظَنَّ @ 2:46[2] → believe
نَبَّأَ @ 3:15[2] → Shall I inform you
شَكَرَ @ 2:52[8] → (be) grateful
حَكَمَ @ 2:113[24] → will judge
يَذَرَ @ 2:234[4] → and leave behind
مَلَكَتْ @ 4:3[23] → possesses
حَسِبَ @ 2:214[2] → (do) you think
شَهِدَ @ 2:84[15] → (were) witnessing
نَادَىٰ @ 3:39[1] → Then called him
أَنذَرَ @ 2:6[6] → whether you warn them
سَبَّحَ @ 2:30[19] → [we] glorify (You)
أُدْخِلَ @ 3:185[14] → and admitted
ٱسْتَطَاعَ @ 2:217[37] → they are able
حَمَلَ @ 2:248[21] → will carry it
عَلَّمَ @ 2:31[1] → And He taught
عَذَّبَ @ 2:284[21] → and He will punish
ٱسْتَكْبَرَ @ 2:34[10] → and was arrogant
بِئْسَ @ 2:90[1] → Evil (is) that
تَرَكَ @ 2:17[13] → and left them
ٱسْتَغْفَرَ @ 2:199[7] → and ask forgiveness
بَلَغَ @ 2:196[15] → reaches
تَوَكَّلْ @ 3:122[11] → let put (their) trust
خَشِىَ @ 2:150[25] → fear them
ٱهْتَدَىٰ @ 2:53[7] → (would be) guided
أَرَيْ @ 2:73[8] → and shows you
حَرَّمَ @ 2:173[2] → He has forbidden
مَّاتَ @ 2:132[13] → (should) you die
رَّضِىَ @ 2:120[2] → will be pleased
بُشِّرَ @ 2:25[1] → And give good news
يَحْزُن @ 2:38[17] → will grieve
نَجَّىٰ @ 2:49[2] → We saved you
حَشَرَ @ 2:203[25] → will be gathered
صَدَّ @ 3:99[5] → (do) you hinder
ذَاقُ @ 3:106[13] → Then taste
رَدَّ @ 2:85[41] → they will be sent back
ٱخْتَلَفَ @ 2:113[31] → differing
ٱسْتَوَىٰٓ @ 2:29[10] → He turned
ذَهَبَ @ 2:17[10] → took away
بَيَّنُ @ 2:68[5] → to make clear
سَجَدَ @ 2:34[4] → Prostrate
نَسِىَ @ 2:44[4] → and you forget
ٱبْتَغَىٰ @ 2:187[26] → and seek
قَامَ @ 2:20[13] → they stand (still)
نَهَىٰ @ 3:104[9] → and forbidding
أَعْرَضَ @ 4:16[8] → then turn away
كَفَىٰ @ 2:137[15] → So will suffice you against them
نَفَعَ @ 2:102[56] → profits them
وَلَّىٰ @ 2:115[5] → you turn
لَبِثَ @ 2:259[25] → (have) you remained
سَآءَ @ 3:120[4] → it grieves them
عَسَى @ 2:216[7] → But perhaps
أَبْصَرَ @ 2:17[17] → (do) they see
أَغْنَتْ @ 3:10[5] → will avail
أَصْبَحَ @ 3:103[17] → then you became
ٱسْتَجَابَ @ 2:186[12] → So let them respond
أَصْلَحَ @ 2:160[4] → and reform[ed]
رَّحِمَ @ 2:286[43] → and have mercy on us
قَدَّمَ @ 2:95[5] → (of what) sent ahead
جَٰهَدَ @ 2:218[6] → and strove
عَصَا @ 2:61[57] → they disobeyed
عَفَا @ 2:52[2] → We forgave
أَفْلَحَ @ 2:189[27] → (be) successful
زَيَّنَ @ 2:212[1] → Beautified
يَشْعُرُ @ 2:9[10] → they realize (it)
بَغَىٰ @ 3:83[4] → they seek
خَلَا @ 2:14[8] → they are alone
جَٰدَلُ @ 4:107[2] → argue
قَدَرَ @ 2:264[29] → they have control
تَوَفَّىٰ @ 2:234[2] → pass away
كَادَ @ 2:20[1] → Almost
أَنجَىٰ @ 2:50[5] → then We saved you
فَتَنُ @ 4:101[15] → (may) harm you
بَدَّلَ @ 2:59[1] → But changed
لَعَنَ @ 2:88[5] → has cursed them
أَذِنَ @ 2:279[4] → then be informed
رَفَعَ @ 2:63[4] → and We raised
أَسْلَمَ @ 2:112[3] → submits
سَخَّرَ @ 13:2[12] → and subjected
أَذَاقَ @ 6:65[18] → and make (you) taste
مَكَرَ @ 3:54[1] → And they schemed
يَرْجُوا۟ @ 2:218[11] → they hope
جَمَعَ @ 3:25[3] → We will gather them
وَهَبَ @ 3:8[8] → and grant
ٱشْتَرَىٰ @ 2:16[3] → bought
أَمَاتَ @ 2:28[8] → He will cause you to die
كَتَمَ @ 2:33[22] → conceal
أَحْسَنَ @ 2:195[10] → And do good
ٱسْتُهْزِئَ @ 2:15[2] → mocks
مَّشَ @ 2:20[8] → they walk
وَضَعَ @ 3:36[2] → she delivered her
أَعَدَّ @ 2:24[12] → prepared
أَنشَأَ @ 6:6[27] → and We raised
تَعَٰلَىٰ @ 6:100[13] → and Exalted
عَرَفَ @ 2:89[20] → they recognized
أَمِنَ @ 2:196[35] → you are secure
بَلَوْ @ 2:155[1] → And surely We will test you
أَقْسَمُ @ 5:53[6] → swore
حَقَّ @ 7:30[4] → deserved
سَعَىٰ @ 2:114[11] → and strives
كَلَّمَ @ 2:118[6] → speaks to us
سَبَقَ @ 7:80[8] → has preceded you
أَحَلَّ @ 2:187[1] → Permitted
قَصَّ @ 4:164[3] → We (have) mentioned them
ٱسْتَعْجَلَ @ 6:57[12] → you seek to hasten
يَضُرَّ @ 2:102[54] → harms them
يَفْقَهُ @ 4:78[35] → (to) understand
نَفَخَ @ 3:49[18] → then I breath
ذُكِّرَ @ 2:282[69] → then will remind
أَوْفَىٰ @ 2:40[8] → and fulfill
أُعِيدُ @ 10:4[11] → He repeats it
أُخْفِىَ @ 2:271[7] → you keep it secret
نِعْمَ @ 2:271[4] → then good
وَفَّىٰٓ @ 2:272[24] → will be repaid in full
تَبَيَّنَ @ 2:109[19] → became clear
مَّتَّعْ @ 2:126[22] → [then] I will grant him enjoyment
عَادَ @ 2:275[39] → repeated
أَسَرَّ @ 2:77[7] → they conceal
أَمْسَكَ @ 2:231[6] → then retain them
وَدَّ @ 2:96[9] → Loves
يَتَفَكَّرُ @ 2:219[26] → ponder
أُغْرِقُ @ 2:50[6] → and We drowned
أَنْعَمَ @ 1:7[3] → You have bestowed (Your) Favors
فَضَّلَ @ 2:47[9] → [I] preferred you
كَرِهَ @ 2:216[9] → you dislike
ٱنقَلَبَ @ 2:143[25] → turns back
أَدْرَىٰ @ 10:16[9] → He (would) have made it known to you
فَصَّلَ @ 6:55[2] → We explain
أَحَاطَ @ 2:81[5] → and surrounded him
قَدَّرَ @ 10:5[8] → and determined for it
سَارَ @ 3:137[6] → then travel
هَاجَرَ @ 2:218[5] → emigrated
فَتَحَ @ 2:76[15] → has
مَنَّ @ 3:164[2] → bestowed a Favor
قَرَأَ @ 7:204[2] → is recited
خَسِرَ @ 4:119[19] → he (has) lost
أُفِكَ @ 5:75[25] → they are deluded
ٱنتَهَىٰ @ 2:192[2] → they cease
بَسَطَ @ 2:245[14] → and grants abundance
ٱسْتَمَعَ @ 6:25[3] → listen
أَنۢبَتَ @ 2:61[15] → grows
وَقَىٰ @ 2:201[12] → and save us
أَتَمَّ @ 2:124[6] → and he fulfilled them
فَرِحَ @ 3:120[8] → they rejoice
غَلَبُ @ 2:249[53] → overcame
صَنَعُ @ 5:14[25] → do
شَرِبَ @ 2:60[20] → and drink
ٱعْتَدَىٰ @ 2:61[59] → transgressing
صَدَقَ @ 2:177[48] → are true
وَعَظْ @ 2:231[36] → He instructs you
غَرَّ @ 3:24[10] → And deceived them
أَغْنَىٰ @ 7:48[9] → (has) availed
أَخَّرَ @ 4:77[34] → You postpone (it for) us
أُوذِىَ @ 3:195[22] → and were harmed
أَتْبَعَ @ 2:262[9] → they follow
أَفْسَدُ @ 2:11[5] → spread corruption
يُبْدِىَ @ 2:33[19] → you reveal
سَكَنَ @ 2:35[3] → Dwell
لَقُ @ 2:14[2] → they meet
عَدَلَ @ 4:3[19] → you can do justice
أَعْتَدَتْ @ 4:18[21] → We have prepared
حَلَلْ @ 2:228[7] → lawful
نَكَحَ @ 2:221[2] → [you] marry
كَشَفَ @ 6:41[4] → and He would remove
كَفَّرَ @ 2:271[13] → And He will remove
أَخْلَفُ @ 2:80[14] → will break
صَرَفَ @ 3:152[30] → He diverted you
وَرِثَ @ 4:11[39] → and inherit[ed] him
تَرَبَّصْ @ 2:228[2] → shall wait
أَسْمَعَ @ 8:23[6] → surely, He (would) have made them hear
زَعَمَ @ 4:60[5] → claim
غَشِيَ @ 3:154[9] → overcoming
سَوَّىٰ @ 2:29[13] → and fashioned them
أَبَى @ 2:34[9] → He refused
مَدَّ @ 2:15[4] → and prolongs them
أَطْعَمَ @ 5:89[19] → you feed
يَصِفُ @ 6:100[15] → they attribute
مَكَّ @ 6:6[9] → We had established them
يَصْلَى @ 4:10[12] → and they will be burned
سَلَكَ @ 15:12[2] → We let it enter
يُنظَرُ @ 2:162[9] → will be reprieved
حَبِطَ @ 2:217[47] → became worthless
مَّنَعَ @ 2:114[4] → prevents
ٱصْطَفَىٰ @ 2:130[11] → We chose him
أَعْلَن @ 2:77[9] → they declare
وَقَعَ @ 4:100[24] → (became) incumbent
قُطِعَ @ 2:27[8] → and [they] cut
ٱسْتَْٔذَنَ @ 9:44[2] → (Would) not ask your permission
تَدْرِى @ 4:11[59] → you know
خَرَّ @ 7:143[30] → and fell down
قَطَّعَ @ 5:33[16] → be cut off
قَعَدَ @ 3:168[4] → while they sat
صَلَّىٰ @ 3:39[5] → praying
يَحْذَرُ @ 2:235[42] → so beware of Him
بَدَأَ @ 7:29[15] → He originated you
حَآجَّ @ 2:76[18] → so that they argue with you
جَحَدُ @ 6:33[14] → they reject
أَوْرَثَ @ 7:43[33] → you have been made to inherit it
طَغَىٰ @ 11:112[8] → transgress
سَقَىٰ @ 2:71[11] → water
زَكَّىٰ @ 2:129[12] → and purify them
أَخْزَيْ @ 3:192[7] → You (have) disgraced him
حَلَفْ @ 4:62[10] → swearing
يُوقِنُ @ 2:4[12] → firmly believe
يَقْرَبُ @ 2:35[13] → [you two] approach
هَادُ @ 2:62[5] → became Jews
بَدَا @ 3:118[16] → (has become) apparent
كَذَبَ @ 2:10[12] → [they] lie
يَسَّرَ @ 19:97[2] → We (have) made it easy
سَخِرَ @ 2:212[6] → and they ridicule
طَبَعَ @ 4:155[15] → (has) set a seal
عَرَضَ @ 2:31[6] → He displayed them
أَذْهَبَ @ 4:133[3] → He can take you away
بَنَىٰ @ 9:110[5] → they built
أَعْجَبَ @ 2:204[4] → pleases you
عَٰهَدَ @ 2:100[2] → they took
وَصَّىٰ @ 2:132[1] → And enjoined
أَنَابَ @ 11:88[35] → I turn
يَنَالُ @ 2:124[17] → reach
لَبَسْ @ 2:42[2] → mix
تَمَتَّعَ @ 2:196[37] → took advantage
يَصِلُ @ 2:27[14] → be joined
تَقَبَّلَ @ 2:127[9] → Accept
ثَبَّتْ @ 2:250[10] → and make firm
حَاقَ @ 6:10[6] → but surrounded
نَزَعَ @ 3:26[9] → and You take away
أَمَدَّ @ 3:124[7] → reinforces you
يُولِجُ @ 3:27[1] → You cause to enter
صَرَّفْ @ 6:46[19] → We explain
صَدَّقَ @ 28:34[10] → who will confirm me
ٱسْتَقَٰمُ @ 9:7[16] → they are upright
ظَهَرَ @ 6:151[26] → (is) apparent
بَخِلَ @ 3:180[4] → withhold
مَرَّ @ 2:259[3] → passed
ٱجْتَبَىٰ @ 3:179[23] → chooses
أَضَاعُ @ 2:143[39] → let go waste
طَلَّقَ @ 2:230[2] → he divorces her
عُذْ @ 2:67[15] → I seek refuge
نَبَذَ @ 2:100[4] → threw it away
فَسَقَ @ 2:59[18] → defiantly disobeying
فَطَرَ @ 6:79[5] → created
أَحْصَىٰ @ 14:34[11] → you will (be able to) count them
أَقْبَلَ @ 12:71[2] → turning towards
يُؤَاخِذُ @ 2:225[2] → will take you to task
ءَاوَىٰٓ @ 8:26[12] → then He sheltered you
ٱنطَلَقَ @ 18:71[1] → So they both set out
طَهَّرَ @ 2:125[17] → [You both] purify
ظَلَّ @ 15:14[7] → and they were to continue
ٱطْمَأَنَّ @ 2:260[15] → to satisfy
قَذَفَ @ 20:39[2] → cast him
يَسْتَحْىِۦٓ @ 2:26[4] → ashamed
يَنطِقُ @ 21:63[9] → speak
فَرَّقُ @ 2:102[38] → [they] causes separation
فَرَضَ @ 2:197[5] → undertakes
يَلْعَبْ @ 6:91[44] → playing
يَقْبَلُ @ 2:48[10] → will be accepted
رَمَىٰ @ 4:112[7] → throws
رَكِبَ @ 11:41[2] → Embark
تَبِعَ @ 2:38[10] → follows
خَاضُ @ 4:140[19] → they engage
وَلَدَ @ 11:72[3] → Shall I bear a child
ٱجْتَنَبُ @ 4:31[2] → you avoid
يُضَٰعِفُ @ 2:245[8] → so (that) He multiplies it
ٱرْتَابَ @ 2:282[95] → you (have) doubt
أَيَّدَ @ 2:87[14] → and We supported him
يَتَسَآءَلُ @ 4:1[21] → you ask
يُسَٰرِعُ @ 3:114[10] → and they hasten
أَمْلَىٰ @ 3:178[6] → We give respite
تَبَارَكَ @ 7:54[29] → blessed
تَفَرَّقَ @ 3:103[6] → be divided
يَطْمَعُ @ 2:75[1] → Do you hope
دَمَّرَ @ 7:137[21] → And We destroyed
يَئِسَ @ 5:3[32] → (have) despaired
طَافَ @ 37:45[1] → Will be circulated
كَفَّ @ 4:77[7] → Restrain
كِيدُ @ 7:195[24] → scheme against me
خَفَّفَ @ 2:86[8] → will be lightened
رَٰوَدُ @ 12:23[1] → And sought to seduce him
زَالَت @ 2:217[30] → they will cease
هَوَىٰ @ 2:87[22] → desire
هَمَّ @ 3:122[2] → inclined
عَجِبُ @ 7:63[1] → Do you wonder
سَمَّىٰ @ 3:36[16] → [I] (have) named her
نَفَرَ @ 4:71[6] → and advance
خَسَفَ @ 16:45[6] → Allah will cave
كَبُرَ @ 4:6[19] → they will grow up
أُجِيبَت @ 2:186[7] → I respond
تَعَالَ @ 3:61[11] → Come
ٱزْدَادُ @ 3:90[7] → they increased
ٱسْتَضْعَفُ @ 7:75[8] → were oppressed
ٱرْتَدَّ @ 2:217[39] → turns away
ٱشْتَهَتْ @ 16:57[7] → they desire
تَزَكَّىٰ @ 20:76[12] → purifies himself
أَظْهَرَ @ 9:33[8] → to manifest it
أَعْطَىٰ @ 9:29[24] → they pay
أَسْقَيْ @ 15:22[8] → and We gave it to you to drink
ٱبْتَلَىٰٓ @ 2:124[2] → tried
يَهْبِطُ @ 2:36[9] → Go down (all of you)
بَٰرَكَ @ 7:137[10] → We blessed
ٱخْتَصَمُ @ 3:44[20] → they (were) disputing
أَغْوَيْ @ 7:16[3] → You have sent me astray
يَنتَظِرُ @ 6:158[35] → Wait
عَمِىَ @ 5:71[5] → so they became blind
أَفَاضَ @ 2:198[10] → you depart
أَنسَىٰ @ 2:106[6] → [We] cause it to be forgotten
ٱضْطُرَّ @ 2:126[25] → I will force him
يَزِرُ @ 6:31[26] → they bear
يُنقَصُ @ 9:4[8] → they have failed you
أَشْهَدَ @ 2:204[9] → and he calls to witness
يَسْتَبْشِرُ @ 3:170[7] → and they receive good tidings
ضَحِكَتْ @ 9:82[1] → So let them laugh
تَنَزَّلَتْ @ 19:64[2] → we descend
تَنَٰزَعُ @ 3:152[11] → and you fell into dispute
عَدَّ @ 14:34[7] → you count
ضَاقَ @ 9:25[16] → and (was) straitened
ٱعْتَزَلَ @ 2:222[7] → so keep away (from)
شَآقُّ @ 4:115[2] → opposes
أُمْطِرَتْ @ 7:84[1] → And We showered
دَامُ @ 3:75[20] → you keep constantly
ٱلْتَقَى @ 3:13[7] → which met
طَّلَعَ @ 5:13[19] → to discover
سِيقَ @ 7:57[14] → We drive them
يَعْمَهُ @ 2:15[7] → they wander blindly
دَلَّ @ 7:22[1] → So he made both of them fall
ٱنتَصَرَ @ 26:93[7] → help themselves
ٱفْتَدَىٰ @ 2:229[33] → she ransoms
حَىَّ @ 7:25[3] → you will live
حَفِظَ @ 4:34[20] → (orders) them to guard
يُكَلِّفُ @ 2:233[18] → is burdened
حَضَرَ @ 2:133[5] → came to
زَاغَ @ 9:117[17] → deviated
تَصَدَّقَ @ 2:280[9] → you remit as charity
بَآءَ @ 2:61[41] → and they drew on themselves
مُلِئَتْ @ 7:18[9] → surely, I will fill
بَلَّغْ @ 5:67[3] → Convey
يَتَمَنَّ @ 2:94[13] → then wish
سَلَّمَ @ 2:233[53] → you pay
نَقَضَتْ @ 2:27[2] → break
يَخْفَىٰ @ 3:5[4] → is hidden
ثُقِفُ @ 2:191[3] → you find them
شَدَدْ @ 10:88[21] → and harden
يَنۢبَغِى @ 19:92[2] → is appropriate
بَوَّأَ @ 3:121[5] → to post
نَزَلَ @ 17:105[4] → it descended
يَسْتَأْخِرُ @ 7:34[8] → seek to delay
يَسْتَفْتُ @ 4:127[1] → And they seek your ruling
أَقْرَضُ @ 2:245[4] → will lend
أَسْرَفَ @ 6:141[27] → (be) extravagant
قَلَّبُ @ 6:110[1] → And We will turn
ٱنتَقَمْ @ 5:95[44] → then will take retribution
فُجِّرَتْ @ 17:91[8] → and cause to gush forth
أَدْرَكَ @ 4:78[3] → will overtake you
فَرَّتْ @ 26:21[1] → So I fled
يُجِيرُ @ 9:6[6] → then grant him protection
ذَرَأَ @ 6:136[4] → He produced
ظَٰهَرُ @ 9:4[11] → they have supported
غَضِبَ @ 4:93[9] → and will fall the wrath
يَصْفَحُ @ 2:109[23] → and overlook
أَسْرَىٰ @ 11:81[9] → So travel
عَهِدَ @ 2:125[12] → And We made a covenant
عَاقَبَ @ 16:126[2] → you retaliate
ٱسْتَمْتَعَ @ 4:24[23] → you benefit[ed]
نَّكَثَ @ 7:135[11] → broke (the word)
وَسِعَ @ 2:255[41] → Extends
بَايَعْ @ 9:111[32] → you have contracted
لَقَّىٰ @ 25:75[6] → and they will be met
زُوِّجَتْ @ 33:37[31] → We married her to you
بَكَتْ @ 9:82[3] → and let them weep
حُمِّلَ @ 2:286[33] → lay on us
بَثَّ @ 2:164[29] → and dispersing
بَطَشْ @ 7:195[8] → (to) hold
خَانُ @ 8:27[5] → betray
خَتَمَ @ 2:7[1] → Has set a seal
خَلَفَ @ 7:142[16] → Take my place
رَجَمْ @ 11:91[14] → surely we would have stoned you
تَبَرَّأَ @ 2:166[2] → will disown
بَرَزَ @ 2:250[2] → they went forth
وَهَنَ @ 3:139[2] → weaken
ذُبِحَ @ 2:67[9] → you slaughter
دَفَعْ @ 3:167[12] → defend
يُفْتِي @ 4:127[6] → gives you the ruling
يُعَمَّرُ @ 2:96[12] → he could be granted a life
دَرَسُ @ 3:79[28] → studying (it)
هَلَكَ @ 4:176[9] → died
آثَرَ @ 12:91[4] → Allah has preferred you
غَلَّ @ 3:161[5] → he defrauds
أَسَآءَ @ 17:7[6] → you do evil
أَرْضَعَتْ @ 4:23[14] → nursed you
ٱقْتَرَبَ @ 7:185[17] → come near
فَرَقْ @ 2:50[2] → We parted
فَرَّط @ 6:31[16] → we neglected
فَصَلَ @ 2:249[2] → set out
ٱكْتَسَبَ @ 2:286[12] → it earned
قَبَضْ @ 2:245[13] → withholds
أَحْصَنَتْ @ 4:25[36] → they are married
أَجْرَمُ @ 6:124[21] → committed crimes
قَرَّبَ @ 5:27[8] → both offered
ٱنشَقَّ @ 19:90[5] → and splits asunder
أَثَارُ @ 2:71[8] → to plough
أَبْلَغُ @ 7:79[6] → I have conveyed to you
ءَانَسَ @ 4:6[8] → you perceive
ٱعْتَصَمُ @ 3:101[11] → holds firmly
أَسْكَن @ 14:14[1] → And surely We will make you dwell
أُكْرِهَ @ 10:99[11] → compel
عَقَرَ @ 7:77[1] → Then they hamstrung
سَلَفَ @ 2:275[34] → (has) passed
أَوْقَدُ @ 5:64[35] → they kindled
سُيِّرَتْ @ 10:22[3] → enables you to travel
أَوْصَٰ @ 4:11[1] → Instructs you
شَرَحَ @ 6:125[6] → He expands
ٱسْتَبَقَ @ 2:148[5] → so race
نَصَحُ @ 7:62[4] → and [I] advise
أَوَى @ 11:43[2] → I will betake myself
ٱسْتَخْلَفَ @ 6:133[8] → and grant succession
أَلَّفَ @ 3:103[14] → then He made friendship
طَعِمُ @ 2:249[17] → taste it
طُمِسَتْ @ 4:47[14] → We efface
عَتَ @ 7:77[3] → and (were) insolent
عَجِلَ @ 7:150[13] → Were you impatient
عَجَّلَ @ 10:11[2] → hastens
يَبْخَسْ @ 2:282[32] → diminish
ٱهْجُرْ @ 4:34[26] → and forsake them
يَمْتَرُ @ 6:2[14] → doubt
يَرْهَقُ @ 10:26[6] → (will) cover
تَقَرَّ @ 19:26[3] → and cool
يَعْتَذِرُ @ 9:66[2] → make excuse
تَوَاصَ @ 51:53[1] → Have they transmitted it to them
تَطَهَّرْ @ 2:222[16] → they are purified
يَجْهَلُ @ 6:111[22] → (are) ignorant
تَّقَطَّعَ @ 2:166[10] → [and] will be cut off
يُؤَدِّ @ 2:283[14] → then let discharge
تَعْثَ @ 2:60[25] → act wickedly
يَعْرُجُ @ 15:14[9] → (to) ascend
جَهَرَ @ 13:10[7] → publicizes
يَشْفَعُ @ 2:255[23] → can intercede
يَرْكَعُ @ 2:43[5] → and bow down
أَصَرُّ @ 3:135[18] → they persist
تَمَّ @ 6:115[1] → And (has been) fulfilled
ٱخْتَارَ @ 7:155[1] → And chose
نَّزَغَ @ 7:200[2] → an evil suggestion comes to you
أُهِلَّ @ 2:173[9] → has been dedicated
يُبْطِلَ @ 2:264[5] → render in vain
تَأْسَ @ 5:26[11] → grieve
مَكَثَ @ 13:17[36] → remains
هَاتُ @ 2:111[14] → Bring
يَسْتَعْتِبُ @ 16:84[14] → will be asked to make amends
عَمَرُ @ 9:17[5] → they maintain
ثَقُلَتْ @ 7:8[5] → (will be) heavy
مَضَىٰ @ 8:38[14] → preceded
يَسْتَقْدِمُ @ 7:34[11] → seek to advance (it)
تَنَٰجَيْ @ 58:8[13] → and they hold secret counsels
سَرَقَ @ 12:77[3] → he steals
يَتَكَلَّمُ @ 11:105[4] → will speak
جَاوَزَ @ 2:249[31] → he crossed it
لَمَسُ @ 4:43[33] → you have touched
بَيَّتَ @ 4:81[7] → plan by night
تَشَٰبَهَ @ 2:70[11] → look alike
عَزَمَ @ 2:227[2] → they resolve
أَقْرَرْ @ 2:84[13] → you ratified
رَبَتْ @ 22:5[64] → and it swells
صَوَّرَ @ 3:6[3] → shapes you
أَنۢبَأَ @ 2:31[10] → Inform Me
صَبَّ @ 22:19[13] → Will be poured
ٱسْتَخْرَجَ @ 12:76[7] → he brought it out
ٱسْتَحَبُّ @ 9:23[10] → they prefer
شَقُ @ 11:106[3] → were wretched
نَذَرْ @ 2:270[6] → you vow
أَلْهَىٰ @ 15:3[4] → and diverted them
يَرْغَبُ @ 2:130[2] → will turn away
ٱرْتَقِبْ @ 11:93[16] → And watch
يَنْحِتُ @ 7:74[15] → and you carve out
شَرَ @ 2:102[69] → they sold
يَدْرَؤُا۟ @ 3:168[10] → Then avert
أَلْحَقْ @ 12:101[20] → and join me
أُغْشِيَتْ @ 7:54[15] → He covers
نَفِدَ @ 16:96[3] → will be exhausted
يَسُومُ @ 2:49[6] → (who were) afflicting you (with)
يَخْرُصُ @ 6:116[18] → guess
ٱسْتَعِذْ @ 7:200[6] → then seek refuge
نَقَمُ @ 5:59[5] → you resent
ٱسْتَعِينُ @ 1:5[4] → we ask for help
ٱسْتَغَٰثَ @ 8:9[2] → you were seeking help
أَكْرَمَ @ 12:21[7] → Make comfortable
سَوَّلَ @ 12:18[8] → has enticed you
أُزْلِفَتْ @ 26:64[1] → And We brought near

In [335]:
df_morph#.columns

,Surah,Ayah,WordIndex,SubIndex,TAG,FORM,Root,Lemma,Arabic,FEATURES,VERB_MAIN,Person,Gender,Number,TAG_Explanation,count,meaning,3MSAP_root
0,1,1,1,1,P,bi,,,بِ,PREFIX|bi+,NOT VERB,None,None,None,Preposition,NaN,NaN,NaN
1,1,1,1,2,N,somi,smw,{som,ٱسْم,STEM|POS:N|LEM:{som|ROOT:smw|M|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN
2,1,1,2,1,PN,{ll~ahi,Alh,{ll~ah,ٱللَّه,STEM|POS:PN|LEM:{ll~ah|ROOT:Alh|GEN,NOT VERB,None,None,None,Proper Noun,NaN,NaN,NaN
3,1,1,3,1,DET,{l,,,ٱل,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
4,1,1,3,2,ADJ,r~aHoma`ni,rHm,r~aHoma`n,رَّحْمَٰن,STEM|POS:ADJ|LEM:r~aHoma`n|ROOT:rHm|MS|GEN,NOT VERB,None,None,None,Adj,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128214,114,6,2,1,DET,{lo,,,ٱلْ,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
128215,114,6,2,2,N,jin~api,jnn,jin~ap,جِنَّة,STEM|POS:N|LEM:jin~ap|ROOT:jnn|F|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN
128216,114,6,3,1,CONJ,wa,,,وَ,PREFIX|w:CONJ+,NOT VERB,None,None,None,Conj.,NaN,NaN,NaN
128217,114,6,3,2,DET,{l,,,ٱل,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
128218,114,6,3,3,N,n~aAsi,nws,n~aAs,نَّاس,STEM|POS:N|LEM:n~aAs|ROOT:nws|MP|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN

In [331]:
import pandas as pd

# Step 1: Load the verbs_with_meanings_roots.xlsx file into a DataFrame
verbs_with_meanings_roots = pd.read_excel("verbs_with_meanings_roots.xlsx")

# Step 2: Load the dp_morph DataFrame (assuming you already have it loaded)
# dp_morph = pd.read_excel("path_to_your_file/dp_morph.xlsx")  # If it's another file

# Step 3: Clean the Arabic columns by trimming spaces
verbs_with_meanings_roots['Arabic'] = verbs_with_meanings_roots['Arabic'].str.strip()
df_morph['Arabic'] = df_morph['Arabic'].str.strip()

# Step 4: Merge the two DataFrames on the "Arabic" column
df_morph = pd.merge(df_morph, verbs_with_meanings_roots[['Arabic', 'count', 'meaning', '3MSAP_root']], on='Arabic', how='left')

In [317]:
merged_df[merged_df['VERB_MAIN']!='NOT VERB']['3MSAP_root'].value_counts()

قَالَ          1618
كَانَ          1358
آمَنَ           537
عَلِمَ          382
جَعَلَ          340
               ...
 خَيَّلَ          1
اِسْتَعْلَى       1
 سَحَتَ           1
 طَارَ            1
 وَقَبَ           1
Name: 3MSAP_root, Length: 1440, dtype: int64

In [333]:
df_morph.groupby('Arabic')['count'].max().sum()

19356.0

In [281]:
import pandas as pd

# 1. Filter to only real verbs
df_filtered = df[df['VERB_MAIN'] != 'NOT VERB'].copy()

# 2. Build a “verse_key” column (e.g. "2:255")
df_filtered['verse_key'] = (
    df_filtered['Surah'].astype(str) + ':' +
    df_filtered['Ayah'].astype(str)
)

# 3. Group by the Arabic word, get count and first occurrence
result = (
    df_filtered
    .groupby('Arabic')
    .agg(
        count=('Arabic', 'size'),
        first_occurrence=('verse_key', 'first')
    )
    .reset_index()
    .sort_values('count', ascending=False)
)

# 4. Write to Excel
output_path = 'verb_counts_first_occurrence.xlsx'
result.to_excel(output_path, index=False)
print(f"✅ Saved {len(result)} rows to {output_path}")
print(result.head(10))

✅ Saved 1475 rows to verb_counts_first_occurrence.xlsx
      Arabic  count first_occurrence
802    قَالَ   1618              2:8
833    كَانَ   1358             2:10
2    ءَامَنَ    537              2:3
743   عَلِمَ    382             2:13
473   جَعَلَ    340             2:19
848   كَفَرَ    289              2:6
467   جَآءَ    278             2:71
746   عَمِلَ    276             2:25
562    رَءَا    271             2:55
220    آتَى    271             2:43

In [661]:
df_morph

,Surah,Ayah,WordIndex,SubIndex,TAG,FORM,Root,Lemma,Arabic,FEATURES,VERB_MAIN,Person,Gender,Number,TAG_Explanation,count,meaning,3MSAP_root
0,1,1,1,1,P,bi,,,بِ,PREFIX|bi+,NOT VERB,None,None,None,Preposition,NaN,NaN,NaN
1,1,1,1,2,N,somi,smw,{som,ٱسْم,STEM|POS:N|LEM:{som|ROOT:smw|M|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN
2,1,1,2,1,PN,{ll~ahi,Alh,{ll~ah,ٱللَّه,STEM|POS:PN|LEM:{ll~ah|ROOT:Alh|GEN,NOT VERB,None,None,None,Proper Noun,NaN,NaN,NaN
3,1,1,3,1,DET,{l,,,ٱل,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
4,1,1,3,2,ADJ,r~aHoma`ni,rHm,r~aHoma`n,رَّحْمَٰن,STEM|POS:ADJ|LEM:r~aHoma`n|ROOT:rHm|MS|GEN,NOT VERB,None,None,None,Adj,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128214,114,6,2,1,DET,{lo,,,ٱلْ,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
128215,114,6,2,2,N,jin~api,jnn,jin~ap,جِنَّة,STEM|POS:N|LEM:jin~ap|ROOT:jnn|F|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN
128216,114,6,3,1,CONJ,wa,,,وَ,PREFIX|w:CONJ+,NOT VERB,None,None,None,Conj.,NaN,NaN,NaN
128217,114,6,3,2,DET,{l,,,ٱل,PREFIX|Al+,NOT VERB,None,None,None,Al+,NaN,NaN,NaN
128218,114,6,3,3,N,n~aAsi,nws,n~aAs,نَّاس,STEM|POS:N|LEM:n~aAs|ROOT:nws|MP|GEN,NOT VERB,None,None,None,Noun,NaN,NaN,NaN

In [17]:
def get_final_ayah_game(surah, ayah):


    
    ayah_data = fetch_quran_ayah(surah, ayah)

    arabic             = ayah_data["arabic_text"]
    english            = ayah_data["english_text"]
    audio              = ayah_data["arabic_audio"]
    surah_name_simple  = ayah_data["surah_name_simple"]
    surah_info_text    = ayah_data["surah_info_text"]
    surah_name_arabic  = ayah_data["surah_name_arabic"]
    surah_name_english = ayah_data["translated_surah_name"]
    urdu               = ayah_data["urdu_text"]
    urdu_audio         = ayah_data["urdu_audio"]
    english_audio      = ayah_data["english_audio"]


    results = parse_quran_with_morphology_df_opt(df_xml, surah, ayah)


    minified_data = minify_all_words(results)

    jarr_phrases = "none"

    generate_quran_game_html_with_extra(
        arabic_text=arabic,
        surah_name=surah_name_simple,
        surah_name_ar=surah_name_arabic,
        ayah_num=ayah,
        english_text=english,
        word_data=minified_data,
        audio_url=audio,
        jarr_phrases=jarr_phrases,
        transliterations=None,
        urdu_text = urdu,
        urdu_audio = urdu_audio,
        english_audio = english_audio,
        required_keys=["Word", "Quran Morph Info", "Conjugation Table", "Audio URL", "VERB_FORM", "tags_joined", "count_of_verb", "root_from_gpt", "Main Verb Grammar","root_from_txt","Meaning Of Verb"],
        output_file = os.path.join(f"surah_{surah}", f"ayah_{surah}_{ayah}.html") 

    )

In [ ]:
#df_morph[df_morph['VERB_MAIN']!='NOT VERB'].Arabic.value_counts()
df_morph[df_morph['Arabic_clean']=='تُدِيرُ']

df_morph[(df_morph['Surah']==2) & (df_morph['Ayah']==282)].head(10)

In [ ]:
#needs correction

import pandas as pd

# Load the text file
gpt_root_df = pd.read_csv("roots_verbs_from_gpt.txt")  # should have Arabic, Count, root

# Clean up Arabic for consistent matching
gpt_root_df['Arabic_clean'] = gpt_root_df['Arabic'].str.strip()
df_morph['Arabic_clean'] = df_morph['Arabic'].str.strip()

# Create dictionaries for mapping
gpt_root_dict = dict(zip(gpt_root_df['Arabic_clean'], gpt_root_df['root']))
gpt_count_dict = dict(zip(gpt_root_df['Arabic_clean'], gpt_root_df['Count']))

# Apply mappings to df_morph
df_morph['root_from_gpt'] = df_morph['Arabic_clean'].map(gpt_root_dict)
df_morph['count_from_gpt'] = df_morph['Arabic_clean'].map(gpt_count_dict)

In [ ]:
unique_sum = (
    df_morph.drop_duplicates(subset='Arabic_clean')
            .set_index('Arabic_clean')['count_from_gpt']
            .dropna()
            .count()
)

print(f"🔢 Sum of counts for unique Arabic words: {unique_sum}")

In [25]:
surah_ayah_counts = {
    1: 7, 2: 286, 3: 200, 4: 176, 5: 120, 6: 165, 7: 206,
    8: 75, 9: 129, 10: 109, 11: 123, 12: 111, 13: 43, 14: 52,
    15: 99, 16: 128, 17: 111, 18: 110, 19: 98, 20: 135, 21: 112,
    22: 78, 23: 118, 24: 64, 25: 77, 26: 227, 27: 93, 28: 88,
    29: 69, 30: 60, 31: 34, 32: 30, 33: 73, 34: 54, 35: 45,
    36: 83, 37: 182, 38: 88, 39: 75, 40: 85, 41: 54, 42: 53,
    43: 89, 44: 59, 45: 37, 46: 35, 47: 38, 48: 29, 49: 18,
    50: 45, 51: 60, 52: 49, 53: 62, 54: 55, 55: 78, 56: 96,
    57: 29, 58: 22, 59: 24, 60: 13, 61: 14, 62: 11, 63: 11,
    64: 18, 65: 12, 66: 12, 67: 30, 68: 52, 69: 52, 70: 44,
    71: 28, 72: 28, 73: 20, 74: 56, 75: 40, 76: 31, 77: 50,
    78: 40, 79: 46, 80: 42, 81: 29, 82: 19, 83: 36, 84: 25,
    85: 22, 86: 17, 87: 19, 88: 26, 89: 30, 90: 20, 91: 15,
    92: 21, 93: 11, 94: 8, 95: 8, 96: 19, 97: 5, 98: 8,
    99: 8, 100: 11, 101: 11, 102: 8, 103: 3, 104: 9, 105: 5,
    106: 4, 107: 7, 108: 3, 109: 6, 110: 3, 111: 5, 112: 4,
    113: 5, 114: 6
}

for surah, count in surah_ayah_counts.items():
    for ayah in range(1, count + 1):
        get_final_ayah_game(surah, ayah)

✅ HTML file generated: output\surah_1\ayah_1_1.html
✅ HTML file generated: output\surah_1\ayah_1_2.html
✅ HTML file generated: output\surah_1\ayah_1_3.html
✅ HTML file generated: output\surah_1\ayah_1_4.html
✅ HTML file generated: output\surah_1\ayah_1_5.html
✅ HTML file generated: output\surah_1\ayah_1_6.html
✅ HTML file generated: output\surah_1\ayah_1_7.html
✅ HTML file generated: output\surah_2\ayah_2_1.html
✅ HTML file generated: output\surah_2\ayah_2_2.html
✅ HTML file generated: output\surah_2\ayah_2_3.html
✅ HTML file generated: output\surah_2\ayah_2_4.html
✅ HTML file generated: output\surah_2\ayah_2_5.html

KeyboardInterrupt:

In [ ]:
from concurrent.futures import ThreadPoolExecutor

tasks = []
for surah, count in surah_ayah_counts.items():
    for ayah in range(1, count + 1):
        tasks.append((surah, ayah))

def run(task):
    s, a = task
    return get_final_ayah_game(s, a)

with ThreadPoolExecutor(max_workers=20) as executor:
    executor.map(run, tasks)

✅ HTML file generated: output\surah_2\ayah_2_4.html
✅ HTML file generated: output\surah_2\ayah_2_7.html
✅ HTML file generated: output\surah_2\ayah_2_8.html
✅ HTML file generated: output\surah_1\ayah_1_4.html
✅ HTML file generated: output\surah_1\ayah_1_3.html
✅ HTML file generated: output\surah_1\ayah_1_6.html
✅ HTML file generated: output\surah_1\ayah_1_1.html
✅ HTML file generated: output\surah_1\ayah_1_7.html
✅ HTML file generated: output\surah_1\ayah_1_2.html
✅ HTML file generated: output\surah_1\ayah_1_5.html
✅ HTML file generated: output\surah_2\ayah_2_9.html
✅ HTML file generated: output\surah_2\ayah_2_5.html
✅ HTML file generated: output\surah_2\ayah_2_11.html
✅ HTML file generated: output\surah_2\ayah_2_12.html
✅ HTML file generated: output\surah_2\ayah_2_2.html
✅ HTML file generated: output\surah_2\ayah_2_6.html
✅ HTML file generated: output\surah_2\ayah_2_13.html
✅ HTML file generated: output\surah_2\ayah_2_1.html
✅ HTML file generated: output\surah_2\ayah_2_3.html
✅ HTML file generated: output\surah_2\ayah_2_10.html
✅ HTML file generated: output\surah_2\ayah_2_14.html
✅ HTML file generated: output\surah_2\ayah_2_16.html
✅ HTML file generated: output\surah_2\ayah_2_15.html
✅ HTML file generated: output\surah_2\ayah_2_24.html
✅ HTML file generated: output\surah_2\ayah_2_18.html
✅ HTML file generated: output\surah_2\ayah_2_19.html
✅ HTML file generated: output\surah_2\ayah_2_21.html
✅ HTML file generated: output\surah_2\ayah_2_22.html
✅ HTML file generated: output\surah_2\ayah_2_23.html
✅ HTML file generated: output\surah_2\ayah_2_34.html
✅ HTML file generated: output\surah_2\ayah_2_17.html
✅ HTML file generated: output\surah_2\ayah_2_36.html
✅ HTML file generated: output\surah_2\ayah_2_25.html
✅ HTML file generated: output\surah_2\ayah_2_29.html
✅ HTML file generated: output\surah_2\ayah_2_35.html
✅ HTML file generated: output\surah_2\ayah_2_30.html
✅ HTML file generated: output\surah_2\ayah_2_27.html
✅ HTML file generated: output\surah_2\ayah_2_20.html
✅ HTML file generated: output\surah_2\ayah_2_26.html
✅ HTML file generated: output\surah_2\ayah_2_33.html
✅ HTML file generated: output\surah_2\ayah_2_37.html

In [ ]:
def get_qutrub_conjugation_test(verb):
    """
    Fetches the conjugation of an Arabic verb from Qutrub API using just the verb.
    
    :param verb: Arabic verb (in Arabic script)
    :return: JSON response with conjugation details or an error message.
    """
    base_url = "http://qutrub.arabeyes.org/api"
    params = {"verb": verb}

    try:
        response = requests.get(base_url, params=params)
        if response.status_code == 200:
            return response.json()
            prit(f"processed {verb}")
        else:
            return {"error": f"API request failed with status code {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}